---

- name: Check if entitlement key already exists
  ansible.builtin.shell: |
    set timeout 300
    {{ directories.bin_dir }}/oc get secret -n {{ instance.namespace }} ibm-entitlement-key 2> /dev/null
    exit 0
  args:
    executable: /bin/bash
  register: query_returnedInfo

- name: Parse returned data to determine if secret already exists
  set_fact:
    secretExists: "{{True if(query_returnedInfo.stdout | length > 0) else False}}"

- name: Create the entitlement key secret
  ansible.builtin.shell:
    cmd: "{{ directories.bin_dir }}/oc create secret docker-registry ibm-entitlement-key --docker-server=cp.icr.io --docker-username=cp --docker-password={{ entitlementKey }} -n {{ instance.namespace }}"
  args:
    executable: /bin/bash
  when: 
    - not secretExists
    - entitlementKey is defined
  register: result